package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

func generate(pkg string, procedures []procedure) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by neo-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\n")
	b.WriteString("\tneo \"github.com/Protocol-Lattice/neo\"\n")
	b.WriteString(")\n\n")

	groups := groupProcedures(procedures)

	b.WriteString("type TypedClient struct {\n")
	b.WriteString("\tclient *neo.Client\n")
	for _, group := range sortedKeys(groups) {
		fmt.Fprintf(&b, "\t%s %sClient\n", exportName(group), exportName(group))
	}
	for _, p := range procedures {
		if !strings.Contains(p.Key, ".") {
			fmt.Fprintf(&b, "\t%s %sProcedure\n", exportName(p.Key), procTypeName(p))
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("func NewTypedClient(addr string, opts ...neo.ClientOption) *TypedClient {\n")
	b.WriteString("\tc := neo.NewClient(addr, opts...)\n")
	b.WriteString("\treturn NewTypedClientFromClient(c)\n")
	b.WriteString("}\n\n")

	b.WriteString("func NewTypedClientFromClient(c *neo.Client) *TypedClient {\n")
	b.WriteString("\ttc := &TypedClient{client: c}\n")
	for _, group := range sortedKeys(groups) {
		fmt.Fprintf(&b, "\ttc.%s = %sClient{client: c}\n", exportName(group), exportName(group))
		for _, p := range groups[group] {
			field := exportName(lastKeyPart(p.Key))
			fmt.Fprintf(&b, "\ttc.%s.%s = %sProcedure{client: c}\n", exportName(group), field, procTypeName(p))
		}
	}
	for _, p := range procedures {
		if !strings.Contains(p.Key, ".") {
			fmt.Fprintf(&b, "\ttc.%s = %sProcedure{client: c}\n", exportName(p.Key), procTypeName(p))
		}
	}
	b.WriteString("\treturn tc\n")
	b.WriteString("}\n\n")

	b.WriteString("func (tc *TypedClient) Metadata(ctx context.Context) ([]neo.ProcedureMeta, error) {\n")
	b.WriteString("\treturn tc.client.Metadata(ctx)\n")
	b.WriteString("}\n\n")

	for _, group := range sortedKeys(groups) {
		fmt.Fprintf(&b, "type %sClient struct {\n", exportName(group))
		b.WriteString("\tclient *neo.Client\n")
		for _, p := range groups[group] {
			fmt.Fprintf(&b, "\t%s %sProcedure\n", exportName(lastKeyPart(p.Key)), procTypeName(p))
		}
		b.WriteString("}\n\n")
	}

	for _, p := range procedures {
		writeProcedureType(&b, p)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), err
	}
	return formatted, nil
}

func writeProcedureType(b *bytes.Buffer, p procedure) {
	typeName := procTypeName(p)
	fmt.Fprintf(b, "type %sProcedure struct {\n", typeName)
	b.WriteString("\tclient *neo.Client\n")
	b.WriteString("}\n\n")

	switch p.Kind {
	case "query":
		fmt.Fprintf(b, "func (p %sProcedure) Query(ctx context.Context, input %s) (%s, error) {\n", typeName, p.Input, p.Output)
		fmt.Fprintf(b, "\treturn p.Call(ctx, input)\n")
		b.WriteString("}\n\n")
		fmt.Fprintf(b, "func (p %sProcedure) Call(ctx context.Context, input %s) (%s, error) {\n", typeName, p.Input, p.Output)
		fmt.Fprintf(b, "\treturn neo.CallTyped[%s, %s](ctx, p.client.Query.Procedure(\"%s\"), input)\n", p.Input, p.Output, p.Key)
		b.WriteString("}\n\n")
	case "mutation":
		fmt.Fprintf(b, "func (p %sProcedure) Mutate(ctx context.Context, input %s) (%s, error) {\n", typeName, p.Input, p.Output)
		fmt.Fprintf(b, "\treturn p.Call(ctx, input)\n")
		b.WriteString("}\n\n")
		fmt.Fprintf(b, "func (p %sProcedure) Call(ctx context.Context, input %s) (%s, error) {\n", typeName, p.Input, p.Output)
		fmt.Fprintf(b, "\treturn neo.CallTyped[%s, %s](ctx, p.client.Mutation.Procedure(\"%s\"), input)\n", p.Input, p.Output, p.Key)
		b.WriteString("}\n\n")
	case "subscription":
		fmt.Fprintf(b, "func (p %sProcedure) Subscribe(ctx context.Context, input %s) (<-chan %s, error) {\n", typeName, p.Input, p.Output)
		fmt.Fprintf(b, "\treturn neo.SubscribeTyped[%s, %s](ctx, p.client.Subscription.Procedure(\"%s\"), input)\n", p.Input, p.Output, p.Key)
		b.WriteString("}\n\n")
		fmt.Fprintf(b, "func (p %sProcedure) SubscribeWebSocket(ctx context.Context, input %s) (<-chan %s, error) {\n", typeName, p.Input, p.Output)
		fmt.Fprintf(b, "\treturn neo.SubscribeWebSocketTyped[%s, %s](ctx, p.client.Subscription.Procedure(\"%s\"), input)\n", p.Input, p.Output, p.Key)
		b.WriteString("}\n\n")
	}
}
