// Code generated by neo-gen; DO NOT EDIT.

package main

import (
	"context"

	neo "github.com/Protocol-Lattice/neo"
)

type TypedClient struct {
	client      *neo.Client
	User        UserClient
	Healthcheck HealthcheckProcedure
}

func NewTypedClient(addr string, opts ...neo.ClientOption) *TypedClient {
	c := neo.NewClient(addr, opts...)
	return NewTypedClientFromClient(c)
}

func NewTypedClientFromClient(c *neo.Client) *TypedClient {
	tc := &TypedClient{client: c}
	tc.User = UserClient{client: c}
	tc.User.Changes = UserChangesProcedure{client: c}
	tc.User.Create = UserCreateProcedure{client: c}
	tc.User.GetByID = UserGetByIDProcedure{client: c}
	tc.Healthcheck = HealthcheckProcedure{client: c}
	return tc
}

type UserClient struct {
	client  *neo.Client
	Changes UserChangesProcedure
	Create  UserCreateProcedure
	GetByID UserGetByIDProcedure
}

type HealthcheckProcedure struct {
	client *neo.Client
}

func (p HealthcheckProcedure) Query(ctx context.Context, input NoInput) (HealthcheckOutput, error) {
	return p.Call(ctx, input)
}

func (p HealthcheckProcedure) Call(ctx context.Context, input NoInput) (HealthcheckOutput, error) {
	return neo.CallTyped[NoInput, HealthcheckOutput](ctx, p.client.Query.Procedure("healthcheck"), input)
}

type UserChangesProcedure struct {
	client *neo.Client
}

func (p UserChangesProcedure) Subscribe(ctx context.Context, input NoInput) (<-chan UserEvent, error) {
	return neo.SubscribeTyped[NoInput, UserEvent](ctx, p.client.Subscription.Procedure("user.changes"), input)
}

type UserCreateProcedure struct {
	client *neo.Client
}

func (p UserCreateProcedure) Mutate(ctx context.Context, input CreateUserInput) (User, error) {
	return p.Call(ctx, input)
}

func (p UserCreateProcedure) Call(ctx context.Context, input CreateUserInput) (User, error) {
	return neo.CallTyped[CreateUserInput, User](ctx, p.client.Mutation.Procedure("user.create"), input)
}

type UserGetByIDProcedure struct {
	client *neo.Client
}

func (p UserGetByIDProcedure) Query(ctx context.Context, input GetUserInput) (User, error) {
	return p.Call(ctx, input)
}

func (p UserGetByIDProcedure) Call(ctx context.Context, input GetUserInput) (User, error) {
	return neo.CallTyped[GetUserInput, User](ctx, p.client.Query.Procedure("user.getByID"), input)
}
