// Code generated by neo-gen; DO NOT EDIT.

package main

import (
	"context"

	neo "github.com/Protocol-Lattice/neo"
)

type TypedClient struct {
	client *neo.Client
	Orders OrdersClient
	Users  UsersClient
}

func NewTypedClient(addr string, opts ...neo.ClientOption) *TypedClient {
	c := neo.NewClient(addr, opts...)
	return NewTypedClientFromClient(c)
}

func NewTypedClientFromClient(c *neo.Client) *TypedClient {
	tc := &TypedClient{client: c}
	tc.Orders = OrdersClient{client: c}
	tc.Orders.Create = OrdersCreateProcedure{client: c}
	tc.Users = UsersClient{client: c}
	tc.Users.Create = UsersCreateProcedure{client: c}
	tc.Users.GetByID = UsersGetByIDProcedure{client: c}
	return tc
}

func (tc *TypedClient) Metadata(ctx context.Context) ([]neo.ProcedureMeta, error) {
	return tc.client.Metadata(ctx)
}

type OrdersClient struct {
	client *neo.Client
	Create OrdersCreateProcedure
}

type UsersClient struct {
	client  *neo.Client
	Create  UsersCreateProcedure
	GetByID UsersGetByIDProcedure
}

type OrdersCreateProcedure struct {
	client *neo.Client
}

func (p OrdersCreateProcedure) Mutate(ctx context.Context, input CreateOrderInput) (Order, error) {
	return p.Call(ctx, input)
}

func (p OrdersCreateProcedure) Call(ctx context.Context, input CreateOrderInput) (Order, error) {
	return neo.CallTyped[CreateOrderInput, Order](ctx, p.client.Mutation.Procedure("orders.create"), input)
}

type UsersCreateProcedure struct {
	client *neo.Client
}

func (p UsersCreateProcedure) Mutate(ctx context.Context, input CreateUserInput) (User, error) {
	return p.Call(ctx, input)
}

func (p UsersCreateProcedure) Call(ctx context.Context, input CreateUserInput) (User, error) {
	return neo.CallTyped[CreateUserInput, User](ctx, p.client.Mutation.Procedure("users.create"), input)
}

type UsersGetByIDProcedure struct {
	client *neo.Client
}

func (p UsersGetByIDProcedure) Query(ctx context.Context, input GetUserInput) (User, error) {
	return p.Call(ctx, input)
}

func (p UsersGetByIDProcedure) Call(ctx context.Context, input GetUserInput) (User, error) {
	return neo.CallTyped[GetUserInput, User](ctx, p.client.Query.Procedure("users.getByID"), input)
}
