// Code generated by neo-gen; DO NOT EDIT.

package main

import (
	"context"

	neo "github.com/Protocol-Lattice/neo"
)

type TypedClient struct {
	client *neo.Client
	Auth   AuthClient
	User   UserClient
}

func NewTypedClient(addr string, opts ...neo.ClientOption) *TypedClient {
	c := neo.NewClient(addr, opts...)
	return NewTypedClientFromClient(c)
}

func NewTypedClientFromClient(c *neo.Client) *TypedClient {
	tc := &TypedClient{client: c}
	tc.Auth = AuthClient{client: c}
	tc.Auth.Login = AuthLoginProcedure{client: c}
	tc.Auth.Register = AuthRegisterProcedure{client: c}
	tc.User = UserClient{client: c}
	tc.User.Me = UserMeProcedure{client: c}
	return tc
}

func (tc *TypedClient) Metadata(ctx context.Context) ([]neo.ProcedureMeta, error) {
	return tc.client.Metadata(ctx)
}

type AuthClient struct {
	client   *neo.Client
	Login    AuthLoginProcedure
	Register AuthRegisterProcedure
}

type UserClient struct {
	client *neo.Client
	Me     UserMeProcedure
}

type AuthLoginProcedure struct {
	client *neo.Client
}

func (p AuthLoginProcedure) Query(ctx context.Context, input LoginInput) (AuthOutput, error) {
	return p.Call(ctx, input)
}

func (p AuthLoginProcedure) Call(ctx context.Context, input LoginInput) (AuthOutput, error) {
	return neo.CallTyped[LoginInput, AuthOutput](ctx, p.client.Query.Procedure("auth.login"), input)
}

type AuthRegisterProcedure struct {
	client *neo.Client
}

func (p AuthRegisterProcedure) Mutate(ctx context.Context, input RegisterInput) (AuthOutput, error) {
	return p.Call(ctx, input)
}

func (p AuthRegisterProcedure) Call(ctx context.Context, input RegisterInput) (AuthOutput, error) {
	return neo.CallTyped[RegisterInput, AuthOutput](ctx, p.client.Mutation.Procedure("auth.register"), input)
}

type UserMeProcedure struct {
	client *neo.Client
}

func (p UserMeProcedure) Query(ctx context.Context, input NoInput) (User, error) {
	return p.Call(ctx, input)
}

func (p UserMeProcedure) Call(ctx context.Context, input NoInput) (User, error) {
	return neo.CallTyped[NoInput, User](ctx, p.client.Query.Procedure("user.me"), input)
}
