// Code generated by neo-gen; DO NOT EDIT.

import { NeoClientCore, type NeoBatchCall, type NeoCallOptions, type NeoClientOptions } from "./neo.runtime.ts";
export { NeoError } from "./neo.runtime.ts";
export type { NeoBatchCall, NeoBatchResult, NeoCallOptions, NeoClientOptions, NeoHeaders, NeoProcedureMeta } from "./neo.runtime.ts";

export interface CreateUserInput {
  name: string;
}

export interface GetUserInput {
  id: number;
}

export interface HealthcheckOutput {
  ok: boolean;
  service: string;
}

export type NoInput = Record<string, never>;

export interface User {
  id: number;
  name: string;
}

export interface UserEvent {
  topic: string;
  name: string;
  data: User;
}

export class TypedClient extends NeoClientCore {
  readonly user: UserClient;
  readonly healthcheck: HealthcheckProcedure;

  constructor(addr: string, options: NeoClientOptions = {}) {
    super(addr, options);
    this.user = new UserClient(this);
    this.healthcheck = new HealthcheckProcedure(this);
  }

}

export function createClient(addr: string, options?: NeoClientOptions): TypedClient {
  return new TypedClient(addr, options);
}

export class UserClient {
  readonly changes: UserChangesProcedure;
  readonly create: UserCreateProcedure;
  readonly getByID: UserGetByIDProcedure;

  constructor(private readonly client: TypedClient) {
    this.changes = new UserChangesProcedure(client);
    this.create = new UserCreateProcedure(client);
    this.getByID = new UserGetByIDProcedure(client);
  }
}

export class HealthcheckProcedure {
  constructor(private readonly client: TypedClient) {}

  query(input: NoInput, options?: NeoCallOptions): Promise<HealthcheckOutput> {
    return this.call(input, options);
  }

  call(input: NoInput, options?: NeoCallOptions): Promise<HealthcheckOutput> {
    return this.client.request<NoInput, HealthcheckOutput>("GET", "healthcheck", input, options);
  }

  toBatchCall(input: NoInput): NeoBatchCall<HealthcheckOutput> {
    return { key: "healthcheck", input };
  }
}

export class UserChangesProcedure {
  constructor(private readonly client: TypedClient) {}

  subscribe(input: NoInput, options?: NeoCallOptions): AsyncIterable<UserEvent> {
    return this.client.subscribe<NoInput, UserEvent>("user.changes", input, options);
  }

  subscribeWebSocket(input: NoInput, options?: NeoCallOptions): AsyncIterable<UserEvent> {
    return this.client.subscribeWebSocket<NoInput, UserEvent>("user.changes", input, options);
  }
}

export class UserCreateProcedure {
  constructor(private readonly client: TypedClient) {}

  mutate(input: CreateUserInput, options?: NeoCallOptions): Promise<User> {
    return this.call(input, options);
  }

  call(input: CreateUserInput, options?: NeoCallOptions): Promise<User> {
    return this.client.request<CreateUserInput, User>("POST", "user.create", input, options);
  }

  toBatchCall(input: CreateUserInput): NeoBatchCall<User> {
    return { key: "user.create", input };
  }
}

export class UserGetByIDProcedure {
  constructor(private readonly client: TypedClient) {}

  query(input: GetUserInput, options?: NeoCallOptions): Promise<User> {
    return this.call(input, options);
  }

  call(input: GetUserInput, options?: NeoCallOptions): Promise<User> {
    return this.client.request<GetUserInput, User>("GET", "user.getByID", input, options);
  }

  toBatchCall(input: GetUserInput): NeoBatchCall<User> {
    return { key: "user.getByID", input };
  }
}

