// Code generated by neo-gen; DO NOT EDIT.

export type NeoHeaders = Record<string, string>;

export type NeoAbortSignal = {
  readonly aborted?: boolean;
  addEventListener?: (type: "abort", listener: () => void, options?: { once?: boolean }) => void;
};

export type NeoCallOptions = {
  headers?: NeoHeaders;
  signal?: NeoAbortSignal;
};

export type NeoRequestInit = {
  method?: string;
  headers?: NeoHeaders;
  body?: string;
  signal?: any;
};

export type NeoReadableStreamReader = {
  read(): Promise<{ done?: boolean; value?: Uint8Array }>;
  releaseLock?: () => void;
};

export type NeoReadableStream = {
  getReader(): NeoReadableStreamReader;
};

export type NeoFetchResponse = {
  readonly ok: boolean;
  readonly status: number;
  text(): Promise<string>;
  readonly body?: NeoReadableStream | null;
};

export type NeoFetch = (input: string, init?: NeoRequestInit) => Promise<NeoFetchResponse>;

export type NeoWebSocketMessageEvent = {
  data: unknown;
};

export interface NeoWebSocket {
  close(): void;
  addEventListener(type: "message", listener: (event: NeoWebSocketMessageEvent) => void): void;
  addEventListener(type: "error" | "close" | "open", listener: () => void): void;
}

export type NeoWebSocketConstructor = new (url: string) => NeoWebSocket;

export type NeoClientOptions = {
  fetch?: NeoFetch;
  headers?: NeoHeaders;
  webSocket?: NeoWebSocketConstructor;
};

type NeoResponse<T> = {
  result?: T;
  code?: string;
  error?: string;
};

declare const TextDecoder: {
  new (): {
    decode(input?: Uint8Array, options?: { stream?: boolean }): string;
  };
};

const maxGETInputBytes = 6 * 1024;

export class NeoError extends Error {
  readonly code: string;
  readonly status: number;

  constructor(code: string, message: string, status: number) {
    super(message);
    this.name = "NeoError";
    this.code = code;
    this.status = status;
  }
}

export interface CreateUserInput {
  name: string;
}

export interface GetUserInput {
  id: number;
}

export interface HealthcheckOutput {
  ok: boolean;
  service: string;
}

export type NoInput = Record<string, never>;

export interface User {
  id: number;
  name: string;
}

export interface UserEvent {
  topic: string;
  name: string;
  data: User;
}

export class TypedClient {
  private readonly baseURL: string;
  private readonly fetchFn: NeoFetch;
  private readonly headers: NeoHeaders;
  private readonly webSocketCtor?: NeoWebSocketConstructor;

  readonly user: UserClient;
  readonly healthcheck: HealthcheckProcedure;

  constructor(addr: string, options: NeoClientOptions = {}) {
    this.baseURL = addr.replace(/\/+$/, "");
    const fetchFn = options.fetch ?? (globalThis as unknown as { fetch?: NeoFetch }).fetch;
    if (!fetchFn) {
      throw new Error("Neo TypeScript client requires a fetch implementation");
    }
    this.fetchFn = fetchFn;
    this.headers = options.headers ?? {};
    this.webSocketCtor = options.webSocket;
    this.user = new UserClient(this);
    this.healthcheck = new HealthcheckProcedure(this);
  }

  async request<In, Out>(
    method: "GET" | "POST",
    key: string,
    input: In,
    options: NeoCallOptions = {},
  ): Promise<Out> {
    let url = this.urlFor(key);
    let requestMethod: "GET" | "POST" = method;
    let body: string | undefined;

    if (method === "GET") {
      if (input !== undefined && input !== null) {
        const rawInput = JSON.stringify(input);
        if (rawInput === undefined) {
          throw new Error("Neo input must be JSON serializable");
        }
        if (rawInput.length > maxGETInputBytes) {
          requestMethod = "POST";
          body = JSON.stringify({ input });
        } else {
          url += (url.includes("?") ? "&" : "?") + "input=" + encodeURIComponent(rawInput);
        }
      }
    } else {
      body = JSON.stringify({ input });
    }

    const response = await this.fetchFn(url, {
      method: requestMethod,
      headers: this.mergeHeaders(options.headers),
      body,
      signal: options.signal,
    });
    const payload = await this.readResponse<Out>(response);
    if (!response.ok || payload.error || payload.code) {
      throw this.toError(payload, response.status);
    }
    return payload.result as Out;
  }

  async *subscribe<In, Out>(
    key: string,
    input: In,
    options: NeoCallOptions = {},
  ): AsyncIterable<Out> {
    const response = await this.fetchFn(this.subscriptionURL(key, input), {
      method: "GET",
      headers: this.mergeHeaders(options.headers, "application/x-ndjson"),
      signal: options.signal,
    });
    if (!response.ok) {
      const payload = await this.readResponse<Out>(response);
      throw this.toError(payload, response.status);
    }
    if (!response.body) {
      throw new Error("Neo subscription response does not expose a readable body");
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    try {
      for (;;) {
        const chunk = await reader.read();
        if (chunk.done) {
          break;
        }
        buffer += decoder.decode(chunk.value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";
        for (const line of lines) {
          const decoded = this.decodeStreamLine<Out>(line);
          if (decoded.hasValue) {
            yield decoded.value;
          }
        }
      }

      buffer += decoder.decode();
      const decoded = this.decodeStreamLine<Out>(buffer);
      if (decoded.hasValue) {
        yield decoded.value;
      }
    } finally {
      reader.releaseLock?.();
    }
  }

  async *subscribeWebSocket<In, Out>(
    key: string,
    input: In,
    options: NeoCallOptions = {},
  ): AsyncIterable<Out> {
    const WebSocketCtor = this.webSocketCtor ?? (globalThis as unknown as { WebSocket?: NeoWebSocketConstructor }).WebSocket;
    if (!WebSocketCtor) {
      throw new Error("Neo WebSocket subscriptions require a WebSocket implementation");
    }

    const socket = new WebSocketCtor(this.webSocketURL(key, input));
    const queue: Out[] = [];
    let done = false;
    let failure: Error | undefined;
    let wake: (() => void) | undefined;
    const notify = () => {
      const resolve = wake;
      wake = undefined;
      resolve?.();
    };

    const abort = () => {
      failure = new Error("Neo request aborted");
      done = true;
      socket.close();
      notify();
    };
    if (options.signal?.aborted) {
      abort();
    } else {
      options.signal?.addEventListener?.("abort", abort, { once: true });
    }

    socket.addEventListener("message", (event) => {
      if (typeof event.data !== "string") {
        return;
      }
      let payload: NeoResponse<Out>;
      try {
        payload = JSON.parse(event.data) as NeoResponse<Out>;
      } catch {
        failure = new Error("Neo WebSocket message was not valid JSON");
        done = true;
        socket.close();
        notify();
        return;
      }
      if (payload.error || payload.code) {
        failure = this.toError(payload, 0);
        done = true;
        socket.close();
        notify();
        return;
      }
      queue.push(payload.result as Out);
      notify();
    });
    socket.addEventListener("error", () => {
      failure = new Error("Neo WebSocket subscription failed");
      done = true;
      notify();
    });
    socket.addEventListener("close", () => {
      done = true;
      notify();
    });

    try {
      while (!done || queue.length > 0) {
        if (queue.length > 0) {
          yield queue.shift() as Out;
          continue;
        }
        if (failure) {
          throw failure;
        }
        await new Promise<void>((resolve) => {
          wake = resolve;
        });
      }
      if (failure) {
        throw failure;
      }
    } finally {
      socket.close();
    }
  }

  private urlFor(key: string): string {
    return this.baseURL + "/" + key.replace(/^\/+|\/+$/g, "");
  }

  private subscriptionURL<In>(key: string, input: In): string {
    let url = this.urlFor(key);
    if (input === undefined || input === null) {
      return url;
    }
    const rawInput = JSON.stringify(input);
    if (rawInput === undefined) {
      throw new Error("Neo input must be JSON serializable");
    }
    return url + (url.includes("?") ? "&" : "?") + "input=" + encodeURIComponent(rawInput);
  }

  private webSocketURL<In>(key: string, input: In): string {
    const url = this.subscriptionURL(key, input);
    if (url.startsWith("https://")) {
      return "wss://" + url.slice("https://".length);
    }
    if (url.startsWith("http://")) {
      return "ws://" + url.slice("http://".length);
    }
    return url;
  }

  private mergeHeaders(extra?: NeoHeaders, accept?: string): NeoHeaders {
    const headers: NeoHeaders = { "Content-Type": "application/json" };
    if (accept) {
      headers.Accept = accept;
    }
    for (const name in this.headers) {
      headers[name] = this.headers[name];
    }
    for (const name in extra ?? {}) {
      headers[name] = extra[name];
    }
    return headers;
  }

  private async readResponse<Out>(response: NeoFetchResponse): Promise<NeoResponse<Out>> {
    const text = await response.text();
    if (text === "") {
      return {};
    }
    try {
      return JSON.parse(text) as NeoResponse<Out>;
    } catch {
      throw new Error("Neo response was not valid JSON");
    }
  }

  private decodeStreamLine<Out>(line: string): { hasValue: boolean; value: Out } {
    const trimmed = line.trim();
    if (trimmed === "") {
      return { hasValue: false, value: undefined as Out };
    }
    let payload: NeoResponse<Out>;
    try {
      payload = JSON.parse(trimmed) as NeoResponse<Out>;
    } catch {
      throw new Error("Neo subscription message was not valid JSON");
    }
    if (payload.error || payload.code) {
      throw this.toError(payload, 0);
    }
    return { hasValue: true, value: payload.result as Out };
  }

  private toError(payload: NeoResponse<unknown>, status: number): NeoError {
    return new NeoError(payload.code ?? "INTERNAL", payload.error ?? "procedure failed", status);
  }

}

export function createClient(addr: string, options?: NeoClientOptions): TypedClient {
  return new TypedClient(addr, options);
}

export class UserClient {
  readonly changes: UserChangesProcedure;
  readonly create: UserCreateProcedure;
  readonly getByID: UserGetByIDProcedure;

  constructor(private readonly client: TypedClient) {
    this.changes = new UserChangesProcedure(client);
    this.create = new UserCreateProcedure(client);
    this.getByID = new UserGetByIDProcedure(client);
  }
}

export class HealthcheckProcedure {
  constructor(private readonly client: TypedClient) {}

  query(input: NoInput, options?: NeoCallOptions): Promise<HealthcheckOutput> {
    return this.call(input, options);
  }

  call(input: NoInput, options?: NeoCallOptions): Promise<HealthcheckOutput> {
    return this.client.request<NoInput, HealthcheckOutput>("GET", "healthcheck", input, options);
  }
}

export class UserChangesProcedure {
  constructor(private readonly client: TypedClient) {}

  subscribe(input: NoInput, options?: NeoCallOptions): AsyncIterable<UserEvent> {
    return this.client.subscribe<NoInput, UserEvent>("user.changes", input, options);
  }

  subscribeWebSocket(input: NoInput, options?: NeoCallOptions): AsyncIterable<UserEvent> {
    return this.client.subscribeWebSocket<NoInput, UserEvent>("user.changes", input, options);
  }
}

export class UserCreateProcedure {
  constructor(private readonly client: TypedClient) {}

  mutate(input: CreateUserInput, options?: NeoCallOptions): Promise<User> {
    return this.call(input, options);
  }

  call(input: CreateUserInput, options?: NeoCallOptions): Promise<User> {
    return this.client.request<CreateUserInput, User>("POST", "user.create", input, options);
  }
}

export class UserGetByIDProcedure {
  constructor(private readonly client: TypedClient) {}

  query(input: GetUserInput, options?: NeoCallOptions): Promise<User> {
    return this.call(input, options);
  }

  call(input: GetUserInput, options?: NeoCallOptions): Promise<User> {
    return this.client.request<GetUserInput, User>("GET", "user.getByID", input, options);
  }
}

